# Insert a blank line between shell prompts
add_newline = true

# Increase the default command timeout to 2 seconds
command_timeout = 2000

palette = "future_shock"

"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](red)\
$os\
$username\
[](bg:peach fg:red)\
$directory\
[](bg:yellow fg:peach)\
$git_branch\
$git_status\
[](fg:yellow bg:green)\
$elixir\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:green bg:sapphire)\
$conda\
[](fg:sapphire bg:lavender)\
$time\
[ ](fg:lavender)\
$cmd_duration\
$line_break\
$character"""

[os]
disabled = false
style = "bg:red fg:crust"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "😡"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:red fg:crust"
style_root = "bg:red fg:crust"
format = '[ $user]($style)'

[directory]
style = "bg:peach fg:crust"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:yellow"
format = '[[ $symbol $branch ](fg:crust bg:yellow)]($style)'

[git_status]
style = "bg:yellow"
format = '[[($all_status$ahead_behind )](fg:crust bg:yellow)]($style)'

[nodejs]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[elixir]
symbol = "😈"
style = "bg:blue"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[c]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[rust]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[golang]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[php]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[java]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[kotlin]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[haskell]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[python]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:crust bg:green)]($style)'

[docker_context]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $context) ](fg:crust bg:sapphire)]($style)'

[conda]
symbol = "  "
style = "fg:crust bg:sapphire"
format = '[$symbol$environment ]($style)'
ignore_base = false

[time]
disabled = false
time_format = "%R"
style = "bg:lavender"
format = '[[  $time ](fg:crust bg:lavender)]($style)'

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[❯](bold fg:green)'
error_symbol = '[❯](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:green)'
vimcmd_replace_one_symbol = '[❮](bold fg:lavender)'
vimcmd_replace_symbol = '[❮](bold fg:lavender)'
vimcmd_visual_symbol = '[❮](bold fg:yellow)'

[cmd_duration]
show_milliseconds = true
format = " in $duration "
style = "bg:lavender"
disabled = false
show_notifications = true
min_time_to_notify = 45000

[palettes.future_shock]
rosewater = "#2C3E50"  # Deep Navy - Base color
flamingo = "#E74C3C"  # Vibrant Red - Accent/Alert
pink = "#F39C12"     # Bright Orange - Accent/Highlight
mauve = "#1ABC9C"    # Refreshing Teal - Accent/Interface
red = "#9B59B6"      # Rich Purple - Accent/UI Element
maroon = "#34495E"   # Darker Navy - for shadows
peach = "#FFC107"    # Yellow - for critical systems
yellow = "#FFD700"    # Laser Yellow - Critical Systems/Alerts
green = "#27AE60"     # Emerald Green - for success/positive feedback
teal = "#1ABC9C"     # Refreshing Teal - for UI elements
sky = "#34495E"      # Dark Navy - for background/shadows
sapphire = "#3498DB"   # Bright Blue - for data/connections
blue = "#8E44AD"     # Deep Purple - for UI elements
lavender = "#D35400"   # Orange-Red - for warnings/errors
text = "#FFFFFF"     # White - for readability
subtext1 = "#EEEEEE"   # Light Gray - for secondary info
subtext0 = "#9E9E9E"   # Medium Gray - for less important text
overlay2 = "#2C3E50"   # Deep Navy - for subtle overlays
overlay1 = "#34495E"   # Dark Navy - for deeper shadows
overlay0 = "#222222"   # Very Dark Gray - for the deepest shadows
surface2 = "#34495E"   # Dark Navy - for metallic surfaces
surface1 = "#2C3E50"   # Deep Navy - for general surfaces
surface0 = "#1A1A1A"   # Almost Black - for the deepest shadows
base = "#2C3E50"      # Deep Navy - Background
mantle = "#2C3E50"     # Deep Navy - Deepest Shadows
crust = "#1A1A1A"      # Almost Black - Absolute Deepest Shadows
